#!/bin/bash
# Multi-cell A/B test runner.
#
# Usage: bash ab_test/run.sh [--cells A,B,D] [--n N] [--seed S]
#   --cells   comma-separated cell IDs from cells.json (default: A)
#   --n       runs per cell (default 5)
#   --seed    RNG seed for the shuffled run order (default 42)
#
# Output: ab_test/results/{YYYYMMDDTHHMMSS-shorthash}[_dirty]/
#   run_meta.json     code version, env, per-cell config
#   run_order.txt     pre-generated shuffled (cell, run_idx) order
#   diff.patch        working-tree diff if dirty
#   {cell_id}/run-{1..N}/
#       cell_meta.json
#       stdout.txt, stderr.txt
#       wall_seconds.txt
#       timer.html               (when produced)
#       sessions/, session.jsonl, plan.json (cell A only)
#
# Cells run in pre-shuffled order to neutralize time-of-day/thermal effects.
# A cell runner may exit 78 to signal "not implemented"; the run continues.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AB_DIR="$ROOT/ab_test"
PROMPT_FILE="$AB_DIR/prompt.md"
RESULTS="$AB_DIR/results"

CELLS="A"
N=5
SEED=42

while [[ $# -gt 0 ]]; do
    case "$1" in
        --cells) CELLS="$2"; shift 2 ;;
        --n)     N="$2"; shift 2 ;;
        --seed)  SEED="$2"; shift 2 ;;
        --help|-h)
            sed -n '2,17p' "$0" | sed 's/^# //; s/^#//'
            exit 0
            ;;
        *)
            echo "unknown arg: $1" >&2
            exit 2
            ;;
    esac
done

mkdir -p "$RESULTS"

RUN_ID=$(python3 "$AB_DIR/run_meta.py" new \
    --results-dir "$RESULTS" \
    --cells "$CELLS" \
    --n-runs "$N" \
    --seed "$SEED" \
    --prompt-file "$PROMPT_FILE")
RUN_DIR="$RESULTS/$RUN_ID"
echo "[run] run_id: $RUN_ID"
echo "[run] run_dir: $RUN_DIR"
echo "[run] cells:   $CELLS  (n=$N each)"

# Look up runner script for a cell from cells.json.
runner_for() {
    local cell="$1"
    python3 -c "
import json, sys
from pathlib import Path
reg = json.loads(Path('$AB_DIR/cells.json').read_text())
print(reg['$cell']['runner'])
"
}

run_one() {
    local cell="$1" idx="$2"
    local runner_rel
    runner_rel=$(runner_for "$cell")
    local runner="$AB_DIR/$runner_rel"
    local out="$RUN_DIR/$cell/run-$idx"

    if [[ ! -x "$runner" ]]; then
        echo "[run] cell $cell run-$idx: runner $runner not executable, skipping" >&2
        return
    fi

    echo "[run] cell $cell run-$idx -> $out"
    mkdir -p "$out"
    local rc=0
    bash "$runner" "$out" "$PROMPT_FILE" || rc=$?
    if (( rc != 0 )); then
        echo "[run] cell $cell run-$idx: runner exited $rc" >&2
        # rc=78 means "not implemented"; keep going.
    fi
}

# Iterate the shuffled order pre-generated by run_meta.py.
while read -r cell idx; do
    [[ -z "$cell" ]] && continue
    run_one "$cell" "$idx"
done < "$RUN_DIR/run_order.txt"

python3 "$AB_DIR/run_meta.py" finish --results-dir "$RESULTS" --run-id "$RUN_ID"

echo ""
echo "All trials complete. Results in: $RUN_DIR"
echo "Next: python3 $AB_DIR/evaluate.py --run-dir $RUN_DIR"
